name: xarray-docs
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - numpy
  - pandas
  - numpydoc
  - matplotlib
  - seaborn
  - dask
  - ipython
  - sphinx
  - netCDF4
  - hdf4=4.2.12  # temporary install to get netCD4 working (GH1106)
  - cartopy
  - rasterio
  - pip:
    - sphinx-gallery
